# -*- coding: utf-8 -*-
"""network_packet_analyser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mwn-tY7Rx-ZvlcHdsaAI1Jm-dS17Adp6
"""

pip install scapy

from scapy.all import sniff, IP, TCP, UDP, Raw

def process_packet(packet):
    if IP in packet:
        ip_src = packet[IP].src
        ip_dst = packet[IP].dst
        protocol = packet[IP].proto

        # Determine the protocol (TCP/UDP)
        if protocol == 6:
            protocol_name = "TCP"
        elif protocol == 17:
            protocol_name = "UDP"
        else:
            protocol_name = "Other"

        print(f"[{protocol_name}] {ip_src} -> {ip_dst}")

        # Display payload data if available
        if Raw in packet:
            payload = packet[Raw].load
            print(f"Payload: {payload}\n")

# Sniff packets (change 'eth0' to your network interface if needed)
sniff(filter="ip", prn=process_packet, store=False)