# -*- coding: utf-8 -*-
"""password_complexity_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBp5fbthVSURev1NZq8kjGRMA_bxvRA7
"""

import re

def check_password_strength(password):
    # Initialize score
    score = 0

    # Length criteria
    if len(password) >= 8:
        score += 1

    # Uppercase criteria
    if re.search(r"[A-Z]", password):
        score += 1

    # Lowercase criteria
    if re.search(r"[a-z]", password):
        score += 1

    # Number criteria
    if re.search(r"[0-9]", password):
        score += 1

    # Special character criteria
    if re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
        score += 1

    # Determine strength based on score
    if score == 5:
        strength = "Very Strong"
    elif score == 4:
        strength = "Strong"
    elif score == 3:
        strength = "Moderate"
    elif score == 2:
        strength = "Weak"
    else:
        strength = "Very Weak"

    return strength

# Example usage
password = input("Enter your password: ")
print(f"Password Strength: {check_password_strength(password)}")